services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheaptripbot
    ports:
      - "5433:5432"
    volumes:
      - cheaptripbotsk_postgres_data:/var/lib/postgresql/data

  cheap_trip_bot:
    build: .
    command: python main.py
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  cheap_trip_scheduler:
    build: .
    command: python -m app.scheduler.scheduler
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  cheaptripbotsk_postgres_data:
